aiven/aiven-client

aiven/client/cli.py
Kafka topic listing returns 'topic_name' instead of 'name'.
=> kafka: update to match latest kafka api changes

aiven/client/cli.py
argparse turns dashes in options into underscores in `Namespace`
attribute names, but in positional arguments they stay as dashes. Fix
parsed argument references to use dashes to avoid `AttributeError`
exceptions.
=> cli: Fix usage of positional arguments containing dashes

aiven/client/argx.py, aiven/client/pretty.py
This makes overriding sys.stdout in mocks, etc work.
=> print_response: resolve `sys.stdout` only when we use it

aiven/client/cli.py
Previously it was not possible to set a two level config option
that had a dot in its name.
This is because the code tried to support unlimited levels of
JSON nesting even though all Aiven user_config values have at
most a single level of nesting.
=> git dcli: for user_config's only support two levels of settings

README.rst, aiven/client/cli.py
`avn service cli <service_name>` starts psql or influx client app and
conencts to given service (or fails if the service isn't InfluxDB or
PostgreSQL).
<service_name> may also be a URL, in which case connection info is
parsed directly from the URL without making any API calls.
Password is passed via environment so that it isn't visible in process
listing.
=> Allow launching PostgreSQL and InfluxDB clients for given service

aiven/client/cli.py, aiven/client/client.py
Project VPC's can be specified for service create and update.
`avn service create --cloud <cloud name> --project-vpc-id <UUID>` will
place the service into a project VPC. Note that the VPC has to be in the
same cloud as the service.
`avn service create --no-project-vpc` puts the service into a public
network in the selected cloud, avoiding the default behavior where the
service would be put into a project VPC if one exists for the project in
that cloud. If there is no VPC in the selected cloud, the argument has
no effect.
The arguments have the same meaning for `avn service update`, except
that omitting the arguments will leave the service in the network it
currently is in (unless a cloud migration is initiated using `--cloud`).
=> service: select project vpc

aiven/client/cli.py, aiven/client/client.py
This supports both fetching of all historical logs of a service that
exists (typically 24 hours) and to tail the service logs for
new entries forever.
=> cli: Add support for new service logs functionality

aiven/client/argx.py
This does not change output for 'avn', 'avn user info' or
'avn unknown-command-here'.
After:
```
$ avn user
usage: avn user [-h] {create,info,login,tokens-expire} ...
positional arguments:
{create,info,login,tokens-expire}
create              Create a user
info                Show current user info
login               Login as a user
tokens-expire       Expire all authorization tokens
optional arguments:
-h, --help            show this help message and exit
```
------
Before:
```
$ avn user
usage: avn [-h] [--config CONFIG] [--auth-ca FILE] [--auth-token AUTH_TOKEN]
[--show-http] [--url URL]
...
optional arguments:
-h, --help            show this help message and exit
--config CONFIG       config file location
'...'
--auth-ca FILE        CA certificate to use [AIVEN_CA_CERT], default None …
```
=> Show help message for relevant level

aiven/client/cli.py, aiven/client/client.py
The `vpc peering-connection delete` command adds support for deleting
peering connections in project VPCs.
=> vpc: delete peering connection

aiven/client/pretty.py
Formats `datetime.timedelta` objects into strings by calling `str()` on
them.
=> pretty: format timedeltas

README.rst, aiven/client/cli.py, aiven/client/client.py
Previously only login and expire all access tokens were supported.
New APIs have since been added to support listing, creating, updating
and revoking individual access tokens.
=> auth: Support new APIs for managing individual access tokens

aiven/client/cli.py, aiven/client/client.py
Initial user of this will be Aiven PostgreSQL upgrade check
but other uses for the tasks concept will follow as well.
=> tasks: add support for upgrade_check

Makefile
Using "pylint" may cause undesireable package downgrades when pylint
versions newer than in Fedora are available.
=> makefile: use python2-pylint and python3-pylint

aiven/client/cli.py, aiven/client/client.py
`service create` command supports --read-replica-for parameter, which
can be used to indicate that the service being created should be a
read replica of the given service. This automatically sets the
appropriate user configuration options for PostgreSQL services and for
other services that use the upcoming read_replica service integration
API that is defined instead.
=> Support easier read replica creation and upcoming API

aiven/client/cli.py
Test output: `python3 -m aiven.client service types -v`
=> service types: improve verbose configuration output

aiven/client/cli.py
The URIs weren't previously shown with any command but are crucial for
being able to connect to those services.
=> Make "service get {service_name} -v" show Kafka auxiliary service URIs

aiven/client/argx.py
Interrupting `avn .. | less` would previously generate a long, ugly
traceback.  This commit instead generates a simple "output truncated"
message, similar to the one we generate on KeyboardInterrupt.
=> argx: avoid outputting a stacktrace when output file is closed

aiven/client/client.py
PR #98 dropped `.../peering-connections` from the URL by accident
=> Fix create VPC peering connection URL

aiven/client/cli.py, tests/test_cli.py
service types -v had slightly prettified printing of list of default
entries.  As it was, all it really did was strip some "s from lists,
but break on dicts. Just calling repr on the whole thing by default is
probably sensible, as even that output matches with what
e.g. json/Python do by default.
=> Fixed service types -v with list of dicts

aiven/client/cli.py, aiven/client/client.py
Introduces the following properties that are mandatory (when applicable)
for Azure VPC peering connections, and optional (if specified, always
`None`) for all other cloud providers:
* `peer_resource_group`: The Azure resource group of the `peer_vpc` VNet
* `peer_azure_app_id`: The Azure AD app object's ID that is used to
create the VNet peering from the user Azure subscription
* `peer_azure_tenant_id`: The AD tenant ID that is the owner tenant of
`peer_azure_app_id`, and to which the Azure subscription
`peer_cloud_account` belongs to.
=> vpc: support azure specific properties

aiven/client/argx.py, aiven/client/pretty.py, tests/test_pretty.py
format_item() was not able to format Decimal objects, and had
trouble with dicts containing decimal or datetime values. Use our
custom JSON encoder in a couple more places to make it more tolerant.
Also add some test cases.
=> Make table prettyprinter handle datetime & decimal types better

.travis.yml, Makefile, README.rst, aiven-client.spec, scripts/avn, setup.py, version.py
Python2 end-of-life is 1st of January 2020. Old versions of aiven-client continue to work for users with no access to python3.
=> Drop python2

version.py
importlib doesn't have load_module and fetching version from version.py
always failed, causing pip installation to fail. Regression from
5bb4c61e9950de4c8c000a4ab02b0c901e0b06ff
=> Fix version reading

aiven/client/cli.py, aiven/client/cliarg.py, aiven/client/client.py
This commit adds the ability to list, create, update, get, delete MirrorMaker replication flows.
Examples:
Create:
```bash
$ avn mirrormaker replication-flow create --project test mirrormaker --source-cluster s --target-cluster t '{"enabled": true, "topics": ["customer\\..*", "warehouse\\.operations"]}'
```
List:
```bash
$ avn mirrormaker replication-flow list --project test mirrormaker
[
{
"enabled": true,
"source_cluster": "s",
"target_cluster": "t",
"topics": [
"customer\\..*",
"warehouse\\.operations"
]
}
]
```
Get one:
```
avn mirrormaker replication-flow get --project test mirrormaker --source-cluster s --target-cluster t
{
"enabled": true,
"source_cluster": "s",
"target_cluster": "t",
"topics": [
"customer\\..*",
"warehouse\\.operations"
]
}
```
Edit:
```
avn mirrormaker …
```
=> Add support for MirrorMaker replication flows

aiven/client/cli.py, aiven/client/client.py
When reconfiguring a Kafka connector with 'avn service connector update',
the new configuration dict had to contain all mandatory config properties
for the connector, even if their values would not change. This made changing
individual options less convenient than it could have been.
Add a new --fetch-current option for the update command. When given,
client will first fetch the connector's current configuration, and then
update it with the given changes, freeing the user from needing to include
any options that don't need to change.
=> Make updating Kafka connector configuration more convenient

.travis.yml, requirements.dev.txt
Update `.travis.yml` to execute the Python test suite on all supported operating systems. Linter checks are configured to run as a separate stage and only on Linux since they should be OS-independent.
isort is version locked below the 5.x series since it is incompatible with the 5.x series it seems.
=> Enable travis builds for multiple operating systems.

.flake8, .pylintrc, .style.yapf, .yapfignore, Makefile, aiven/client/argx.py, aiven/client/cli.py, aiven/client/cliarg.py, aiven/client/client.py, aiven/client/envdefault.py, aiven/client/pretty.py, requirements.dev.txt, setup.py, tests/test_cli.py, tests/test_pretty.py, version.py
aiven-client did not implement any code-formatting style other then enforcing isort.
As a result this is a "rip the bandaid off" PR which implements `yapf ==0.27.0` as the code-formatting style for this library and reformats all the existing code to match it.
pylint and flake8 are updated to ensure a consistent formatting experience. The sequence: `make reformat && make test` now represents commitable, passing PRs.
=> Add the yapf code formatter

aiven/client/argx.py, aiven/client/cli.py
This adds a bit of documentation to `arg`, the intention is to make it a bit easier to understand it's usage.
=> Documentation for decorator arg

aiven/client/cli.py, aiven/client/client.py
Displays invited users which aren't displayed in the list-user command.
```
$ avn project invite-list --project ovo-uat
```
```
INVITED_USER_EMAIL    INVITING_USER_EMAIL     MEMBER_TYPE  INVITE_TIME
===================== ======================  ===========  ====================
bob@example.com       admin@example.com       read_only    2020-10-16T12:17:47Z
alice@example.com     admin@example.com       read_only    2020-10-16T12:17:48Z
eve@example.com       admin@example.com       read_only    2020-10-16T12:17:46Z
```
=> Add cli and client command to list invites

aiven/client/argx.py, tests/test_argx.py
When using argx to build multiple tools, the subcommands weren't being
kept sorted. This patch ensures that the ordering of subcommands is
always alphabetical as opposed to based on the order of loading (which
is not consistent).
=> argx: Sort subcommands alphabetically

aiven/client/cliarg.py
`name` is quite broad and sometimes it is hard to tell what name is necessary from the context, examples:
```
avn service keypair get --key-filepath /tmp/keyfile --cert-filepath /tmp/certfile
usage: avn service keypair get [-h] [--project PROJECT] --key-filepath
KEY_FILEPATH --cert-filepath CERT_FILEPATH
name keypair
avn service keypair get: error: the following arguments are required: name, keypair
```
and
```
avn service ca get --target-filepath /tmp/test.ca
usage: avn service ca get [-h] [--project PROJECT] --target-filepath
TARGET_FILEPATH
name ca
avn service ca get: error: the following arguments are required: name, ca
```
Calling the argument `service_name` should make it slightly easier to guess what value should be used.
=> cli: self describing name

aiven/client/cli.py, aiven/client/client.py
The service group concept has been removed on backend side. The API
still accepts and returns the related fields but the input is always
ignored and output is hardcoded dummy value. Remove it also from the
cli except for service create and update commands so that backwards
compatibility is kept.
Note that the Python library change is backwards incompatible as it
was not possible to make the parameter optional while retaining
compatibility.
=> Deprecate / remove service group concept

aiven/client/argx.py
Currently, `---format` fails for `service get` with the following Exception:
``TypeError: format() argument after ** must be a mapping, not str``
This change fixes `--format` for all calls to `print_response` when `single_item` is `True`
EDIT:
Added fix for csv output as well
=> cli: fix format for single item

aiven/client/cli.py, tests/test_cli.py
User creation throws an exception when Redis ACL options are not provided.
Also, added a simple test case for this.
=> cli: fix user creation regression

aiven/client/cli.py
Make --project required for `avn service integration_types` and
`avn service integration_endpoint_types`. Fixes #153
(I'm not sure if there's a better way to extend the existing `@arg.project` definition, very happy to refactor if another approach is recommended).
=> Update project name finding for endpoints that were erroring

README.rst
Having `aiven.com` in the example is especially weird since https://aiven.com/ belongs to some random company...
=> Small fixes to README

.github/workflows/build.yaml
We moved the builds to GitHub Actions, but we didn't update to include the current version of Python, 3.9. This is now included.
=> Add python 3.9 to the build matrix

.github/workflows/build.yaml
Currently we trigger the workflow file for every push and pull request event. For example, every time we create a PR we run 2x, when we create a branch we run, etc.
Is this the goal? Or shoud we start using the following conditions?
- `push`: trigger only when we merge to master
- `tags`: every time we create a tag
- `pull request`: every time we create and update a pull request
=> gh_actions: only trigger in pull requests/tags and add filter for push

.github/workflows/publish-pypi.yaml
Add GitHub Action that publishes to PyPI based on pushed annotated tag. The secret has been set up, so this is ready to use.
=> Publish to PyPI with GitHub Action

.github/workflows/publish-pypi.yaml
Only start Publish to PyPI GitHub Action for tags to reduce unnecessary duplicating build workflows.
=> Don't start PyPI publish action unnecessarily

aiven/client/client.py
Add default value for call parameters to keep client API backward compatible so this can be used as Python lib also, not only CLI tool.
=> Add default tags for service_topic_create client call

.github/CONTRIBUTING.md, .github/ISSUE_TEMPLATE/01_question.md, .github/ISSUE_TEMPLATE/02_bug.md, .github/ISSUE_TEMPLATE/03_feature.md, .github/ISSUE_TEMPLATE/config.yml, .github/PULL_REQUEST_TEMPLATE.md
Add some helper files to orientate and encourage new contributors to the project. Includes: 
- a contributing file, which prompts when someone opens a pull request for the first time
- a pull request template to remind everyone to explain what the change is and why we care
- a set of issue templates for bugs/features/questions to help get the right information for each type (blank issues are still enabled)
=> Add basic contributing and issue/PR template files

README.rst, aiven/client/cli.py
For users with platform authentication disabled the `avn login` command
cannot authenticate the aiven-client. This authentication method may
have been excluded by admins at the account level.
To authenticate the client the user could edit the JSON configuration
file to add an authentication token directly, but by accepting it also
in the `avn login` command we can make the functionality more easily
discoverable.
=> cli: accept token in avn login command

README.rst
Sometimes a user registered through the AWS or GCP marketplace. Add a note to mention that `--tenant` is needed in the `user login` command otherwise they will get a `User does not exist` error.
=> Mention usage of tenant argument in login command

aiven/client/cli.py, aiven/client/cliarg.py, tests/test_cliarg.py
Added "--user-config-json" parameter to support json in specifying
more complex user config for commands. The json document is checked
against schema in Aiven API, cli does only basic syntactic check.
The new parameter can be added with a decorator `user_config_json()`
found in aiven/client/cliarg.py:43
Currently the parameter is implemented for service integration related
commands.
Unit tests for the decorator are in tests/test_cliarg.py
=> Add custom datadog tags

README.rst
Added section to README.rst containing some links to help.aiven.io articles
and short description of all service integration related commands.
README was missing documentation of commands related to service integration. The links
to help.aiven.io are included to provide explanation about the purpose of the service integration
feature and offer concrete examples how the service integration commands could be used.
=> README: add section for service integration commands

aiven/client/cli.py, aiven/client/client.py, aiven/client/session.py, tests/test_session.py
This allows the user to specify a maximum duration for a connection to be established and request responded to. This is helpful in automated processes where you want to limit the amount of time spent waiting, as it may indicate connectivity issues that is handled separately.
=> Add global --request-timeout arg

aiven/client/cli.py, aiven/client/client.py
Added parameter `--use-source-project-billing-group` to control
billing group creation when doing a copy from existing project.
When used, the new project will use the same billing group as
the source project.
=> jhonkola: add parameter to project creation

aiven/client/session.py, requirements.dev.txt
Downstream we were not able to build this because of a pylint error that CI didn't catch:
```
aiven/client/session.py:16:4: W0222: Signature differs from overridden 'send' method (signature-differs)
```
This ended up being because the downstream builds are using an older version of pylint (as provided by fedora 33 repos) that catches this issue, but the GHA CI was using an unpinned version of pylint (and therefore the newest version pip can find). I've pinned the version of pylint to our downstream use case to prevent this in the future, and added a disabler for the offending method.
=> ci: use python 3.9 for linting

aiven/client/argx.py
This is for allowing running argx based CLI from Python console.
=> argx: add args argument to main function of argx

aiven/client/argx.py
In some cases it can be useful to pass an already instantiated parser
instance to the CommandLineTool, so allow this if needed.
This can be used to extend the tool with additional commands sourced elsewhere.
=> argx: allow passing a parser to CommandLineTool

aiven/client/argx.py
As the default is None, this paramater should have been defined as
Optional, so fix this up.
The type hints were incorrect so fix them up.
=> argx: make parser optional

aiven/client/cli.py, aiven/client/client.py, tests/test_cli.py
* Added migration_check support to `service task-create` command
* Added command to check the status of a task - `service task-get`
* Updated list of supported PG versions for upgrade check (renamed target version parameter to match the style)
=> Add migration check support and update PG versions for upgrade_check [BF-597]

README.rst
There are a few cases in the README file that hyperlink was written using the markdown syntax
=> Fix hyperlink syntax

aiven/client/cliarg.py, tests/test_cliarg.py
Fix bug in `--user-config-json` parameter validation that caused an error
when `-c` parameter was used even if `--user-config-json` was not.
=> cliarg: fix false parameter conflict bug

aiven/client/cli.py, aiven/client/connection_info/__init__.py, aiven/client/connection_info/_utils.py, aiven/client/connection_info/common.py, aiven/client/connection_info/kafka.py, aiven/client/connection_info/pg.py, aiven/client/pretty.py
Examples:
```
postgres://avnadmin:lfkjJfjQ6vQIG7Xr@privatelink-mypg.aiven.domain:21089/defaultdb?sslmode=require
kafkacat -b mykafka.aiven.domain:21100 -X security.protocol=SASL_SSL -X ssl.ca.location=ca.pem -X sasl.mechanisms=SCRAM-SHA-256 -X sasl.username=mwf -X sasl.password=eTKOcEM8ulGG4nCa
```
=> Connection information commands for kafkacat and psql

aiven/client/cli.py, tests/test_cli.py
This PR is intended to improve service EOL support in the cli's commands
Notably:
* If a specific version is provided to `service create` or `service update` command some sanity checks are peformed, checking EOL status of the service  and asking for confirmation if needed before proceeding
* `service list` command now shows EOL notifications
=> Improve support around service EOL

aiven/client/cli.py
Card security code can start with zero, so handling it as integer is not
appropriate. Use string so that leading zeroes are preserved.
Allows adding card when CVC starts with zero
=> Fix arg type to support card CVC with leading zero

aiven/client/cli.py
The EOL notification formatting for `service list` was statically displaying:
`EOL: 2021-11-11 Upgrade available`
when an EOL notification was present on a service, it will now show:
`EOL: 2021-11-11 Upgrade required`
when the notification is of "warning" level, matching what the web UI does.
=> Show "upgrade required" when EOL notification is of "warning" level

aiven/client/cli.py, aiven/client/client.py
Kafka service can be switched to Karapace only for REST API and schema registry if not yet migrated.
=> Add --use-karapace to service update args

CODE_OF_CONDUCT.md
We don't have the code of conduct in this project yet, so add it (contributor covenant, as we use for our other projects). This is an important commitment that we make to our community and contributors.
=> Add the code of conduct

aiven/client/cli.py, aiven/client/client.py, tests/test_cli.py
We support unpinned connection pools (reusing the pool user to connect
to the database) on the platform for a while now. This adds client support
for creating unpinned pools and for unpinning existing pools.
=> add support for unpinned connection pools [BF-552]

aiven/client/cli.py, aiven/client/client.py
In Flink backend were added new options for Flink table creations:
- key format for kafka
- value format for kafka
- kafka conntector type
- startup mode for kafka
- detaled columns type for tables
Colums info is in a json array and look a bit ugly and make reading harder in a table layout.
That is why, I did incude colums when customer request one table info or create a table but excluded from a table lists:
With columns:
Without columns:
Without columns it is easier to read table ids and schema.
=> flink: support new versions of API methods [HH-690]

aiven/client/cli.py, aiven/client/client.py
When a user certificate is renewed we email the project contacts to advise them to update the certificates in their Kafka clients. WE may do this periodically. There is a new API call to indicate that this step has been done and avoid follow-up emails. This PR adds a CLI command to invoke the API. The command is:
```
avn service user-creds-acknowledge ${SERVICE_NAME} --username ${USERNAME}
```
This name matches the CLI command to download the credentials: `user-creds-download`
=> Add command to acknowledge certificate update

.github/CODEOWNERS
This change should make PR reviews faster.
=> Add dark-matter team to CODEOWNERS

aiven/client/cli.py, tests/test_cli.py
Fix #246
The result of `get_project` is `None` if user didn't login, and specifies `--auth-token`. Check and raise an exception.
=> Show an error when project is not supplied

Makefile, aiven/client/cli.py
Instead of hard coding the supported versions just make sure the version
consists of digits only. The API will not accept invalid versions anyway.
This will allow performing the upgrade_check for - and subsequently
upgrading to - pg14 (and upcoming versions, as soon as they are offered).
=> pg: don't hard code major versions in upgrade_check task

Makefile, aiven/client/cli.py
https://github.com/aiven/aiven-client/pull/247 introduced a bug: an error about a missing project was raised even if the project was optional.
This change fixes this by splitting get_project to get_non_none_project and get_project.
=> Do not raise an error about the missing project in non-auth commands

README.rst
Changed domain for certifi to go to Github repo for python package (direct link to certifi.io  returns a 403)
=> Update broken certifi link in README

.github/workflows/build.yaml, Makefile, aiven-client.spec, aiven/__init__.py, aiven/client/__main__.py, aiven/client/argx.py, mypy.ini, requirements.dev.txt
This change is the beginning of fully annotating Aiven Client. Install
mypy, add mypy config file with everything ignored, except for the one
module, add target to Makefile, enable checks in GitHub Actions.
Partial implementation of #258.
=> typing: add type checks for the first module

README.rst
File is located:
https://github.com/aiven/aiven-client/blob/master/.github/CONTRIBUTING.md
It is easier to find when it is located on the README
as the intention is to provide information for new
contributors, so this section may be useful. 
Therefore, this PR proposes this.
=> Link contributing file to readme file

.github/workflows/build.yaml, README.rst, setup.py
Python 3.6 recently reached its end-of-life:
https://devguide.python.org/devcycle/#end-of-life-branches
=> Drop Python 3.6 support

aiven/client/cli.py, aiven/client/client.py
Add `opensearch_index` parameter to Flink table create API.
Testing:
```
$ ./scripts/avn service flink table create --project systest-project flink-flink-e2e-os-s068untw "d247af5d-daec-4629-a7bf-699f7201539f"  --opensearch-index index1 -s "id INT" -n "t1"
INTEGRATION_ID                        TABLE_ID                              TABLE_NAME  SCHEMA_SQL  COLUMNS                                             
====================================  ====================================  ==========  ==========  ====================================================
d247af5d-daec-4629-a7bf-699f7201539f  37fa3ba1-28d4-4a10-bc49-adda8b1d1a4a  t1          id INT      {"data_type": "INT", "name": "id", "nullable": true}
```
And the table `t1` can be seen in the Console UI, in the tables list when …
=> flink: add opensearch_index to create table parameters

.flake8, .github/workflows/build.yaml, Makefile, aiven/client/pretty.py
Building packages for Fedora 35 (`python 3.10.2`) breaks with:
```
+ make test
make[3]: Entering directory '/var/home/vladan/rpmbuild/BUILD/aiven-client'
fatal: not a git repository (or any parent up to mount point /var/home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: not a git repository (or any parent up to mount point /var/home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: not a git repository (or any parent up to mount point /var/home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
python3 -m flake8 aiven tests
aiven/client/client.py:1619:5: C901 'AivenClient.create_project' is too complex (12)
aiven/client/client.py:1675:5: C901 'AivenClient.update_project' is too complex (12) …
```
=> Increase complexity threshold when linting

aiven/client/cli.py, aiven/client/pretty.py, tests/test_pretty.py
In `service__user_get()`, avoid displaying Redis ACLs if they aren't present in user data - this
was previously causing exceptions if displaying other types of user, e.g. a Postgres user:
```
File "/home/hugh.cole-baker/Source/aiven-client/aiven/client/cli.py", line 1764, in service__user_get
self.print_response(user, single_item=True, format=self.args.format, json=self.args.json, table_layout=layout)
File "/home/hugh.cole-baker/Source/aiven-client/aiven/client/argx.py", line 257, in print_response
pretty.print_table(
File "/home/hugh.cole-baker/Source/aiven-client/aiven/client/pretty.py", line 168, in print_table
for row in yield_table(result, drop_fields=drop_fields, table_layout=table_layout, header=header):
File "/home/hugh.cole-baker/Source/aiven-client/aiven/client/pretty.py", line …
```
=> cli: fix service user-get command

.pylintrc, aiven/client/argx.py, aiven/client/cli.py, aiven/client/cliarg.py, requirements.dev.txt
Fix #266.
After introducing more tests, the `format()` function will be replaced
with f-strings.
=> Update dev requirements

Makefile, aiven/client/session.py, mypy.ini, requirements.dev.txt
Add type annotation on the following
files:
aiven/client/common.py
aiven/client/envdefault.py
aiven/client/session.py
aiven/client/version.py
Signed-off-by: laysa.uchoa <laysa.uchoa@aiven.io>
Co-authored-by: Roman Inflianskas <rominf@aiven.io>
It is related to this Issue: https://github.com/aiven/aiven-client/issues/258
=> Add type annotation for some files

.github/workflows/build.yaml
`pypy3` stands for Python 3.6, which was dropped recently.
=> Use pypy-3.7 and pypy-3.8 on CI

aiven/client/cli.py
The variable doesn't seem to have any effect except polluting base
arguments in subclients. If similar functionality is needed, a
(multiple) class inheritance approach should be considered instead
(`super().method()` in all subclasses adding their plugin specific
features).
=> drop PLUGINS global variable

aiven/client/speller.py, mypy.ini, tests/test_speller.py
Add type annotations to:
Part of https://github.com/aiven/aiven-client/issues/258
=> Add type annotations to `aiven.client.speller` and `tests/test_speller.py`

aiven/client/cli.py, aiven/client/connection_info/redis.py
This PR add support for Redis services to the `cli` and `connection-info` commands to make it easier to interact with a Redis service in the command line with the help of the `avn` client.
=> Add support for Redis services in `cli` and `connection-info` commands

aiven/client/cli.py, aiven/client/client.py, tests/test_cli.py
Adds ability to configure OAuth2 apps for users.
As we are moving to allow third-party providers to integrate with aiven services it's helpful to have convenient interface to configure oauth2 apps.
=> Add initial support for creating OAuth2 apps

aiven/client/cli.py, aiven/client/cliarg.py, aiven/client/client.py
This PR adds the support of new table creation API for Aiven for Apache Flink service.
Command line has new parameter `--table-properties` which takes a JSON string or a path to JSON file.
Old API is removed.
=> Add support for new Flink table creation API

.github/workflows/build.yaml, .github/workflows/publish-pypi.yaml
This patch improves security around GitHub Workflows:
For the `build.yml` workflow:
* Set the default workflow permissions to `read` - because this workflow does not need to modify anything in the project.
* Do not let `actions/checkout` persist (write to disk) the GitHub token - because this workflow does not need to modify anything in the project. And prevents other actions to look at the token.
For the `publish-pypi.yaml` workflow:
* Set the default workflow permissions to `read` - because this workflow does not need to modify anything in the project.
* Do not let `actions/checkout` persist (write to disk) the GitHub token - because this workflow does not need to modify anything in the project. And prevents other actions to look at the token.
* Pin the …
=> Harden the GitHub Workflows [SECDEV-678]

aiven/client/cli.py
Oauth2 commands were added in parallel with another commit adding typing to cli module and slipped through.
=> Add missing type annotations to aiven cli oauth2 commands

aiven/client/cli.py, aiven/client/client.py
Add support for Kafka Schema Registry authorization.
Add commands to add, list and delete Schema Registry ACL entries.
Add parameters to service update call to be able to toggle authorization on and off.
=> Add support for Kafka Schema Registry ACL

aiven/client/cli.py, tests/test_cli.py
If the user is creating/updating a service in a cloud that has a VPC, and they have specified the cloud with `--cloud`, and they have not specified either `--project-vpc-id=<id>` or `--no-project-vpc`, then stop with an error asking them to do one or the other.
Fixes: https://github.com/aiven/aiven-client/issues/290
When a new service is created at the console, it will be created in "Public Internet" even if there is a VPC available.
When `avn service create` is used to create a new service, it will default to using a VPC if there is one available in the target cloud. This is unexpected, and can lead to (for instance):
```
avn service cli <pg-service-name>
```
giving an error like
```
psql: error: could not translate host name "<pg-service-name>" to address: nodename nor servname …
```
=> Ask user to be specific when there is a VPC

MANIFEST.in, setup.py
Even though package was fully type annotated, it was not PEP 561 compatible:
https://mypy.readthedocs.io/en/latest/installed_packages.html#creating-pep-561-compatible-packages
This change fixes the issue.
=> Make package PEP 561 compatible

.github/workflows/build.yaml
pip==21.2.4 is the latest version that doesn't enforce PEP 440.
This is a temporary solution to unblock PRs.
=> Temporary pin pip version in GitHub Actions to allow our way of versioning

.github/workflows/build.yaml
pypy has a version for Python 3.9, let's use it.
=> Add pypy-3.9 to GitHub Actions

.github/workflows/build.yaml
macOS is quite popular among developers, let's test our client on it.
=> Add macOS to GitHub Actions

aiven/client/cli.py
- Add 30s of timeout to the get Stripe tokens POST request.
Failing CI jobs due this Pylint warning:
- https://github.com/aiven/aiven-client/runs/8135685364?check_suite_focus=true
- https://github.com/aiven/aiven-client/runs/8187706530?check_suite_focus=true
- https://pylint.pycqa.org/en/latest/user_guide/messages/warning/missing-timeout.html
- https://aiven-io.slack.com/archives/C01F71NSJG2/p1662385160601659
=> Add 30s of timeout to the get Stripe tokens POST request

README.rst, aiven/client/cli.py, aiven/client/connection_info/kafka.py
Kafkacat is the old name of the tool now named [kcat](https://github.com/edenhill/kcat), the PR adds the functions to retrieve the kcat call, we'll be then able to deprecate the `kafkacat` one and remove it safely some time in the future
=> Adding connection-info kcat support in aiven-client

aiven/client/__init__.py
In client projects, mypy complains about Client not being explicitly exported.
This change adds the explicit export.
=> client: add explicit export

aiven/client/cli.py, aiven/client/client.py
This patch adds support for `avn account team invite-delete` to delete a (pending) invite.
> In the API documentation this functionality is referred to as "Cancel pending user invite" - should the command follow that terminology and be `avn account team invite-cancel` ?
=> cli: add support for deleting pending invites

aiven/client/cli.py, aiven/client/client.py
Add support for the upcoming beta feature of 'privatelink' support for services in running in Google cloud. This enables creating and managing what Google call 'Private Service Connect' connections in the same way as with similar AWS and Azure features.
=> Add support for managing privatelink connection for Google services

aiven/client/argx.py, aiven/client/cliarg.py
This change introduces a hint for mypy about dynamic attributes of `arg`.
=> Fix arg typing

.github/workflows/build.yaml
Currently main build is broken:
1. Checkout Action does shallow fetch.
2. `pip` tries to install the package.
3. `setup.py` tries to generate version using `version.py`.
4. `version.py` executes `git describe`.
5. `git` outputs hash instead of tag + hash because the last commit is
not tagged.
6. `version.py` expects tag + hash to extract the version and raises and
exception.
This change changes fetching to get full history. 
Tested by cloning and observing `git describe` (locally).
=> Fix main build

.github/workflows/build.yaml
=> Build against python 3.11

.github/workflows/build.yaml
We use Fedora 37 downstream, so to find bugs earlier, let's test Aiven Client on Fedora 37 too.
=> Add Fedora 37 to GitHub Actions

aiven/client/client.py
In the current implementation, if show_http is False, level ends up as NOTSET, which causes all messages to be processed.
By defaulting to INFO, we will hide all the debug messages unless show_http excplicitly is enabled.
=> client: fix log level

aiven/client/argx.py, tests/test_argx.py
`Argparse` parsers use `description` to access the overall help for a command, unlike the `add_argument` calls which use the `help` attribute.
Without this, the general description on what a sub-command is to be used for is lost when running with `--help`
Documentation: https://docs.python.org/3/library/argparse.html#description
=> Set sub-command cli description 

tests/test_argx.py
Fix the pylint failure from overwriting the builtin `help` https://github.com/aiven/aiven-client/actions/runs/5396648798
=> Fix failures introduced in #343

aiven/client/cli.py
New command for creating organizations. It receives the organization's name. The command asks for confirmation that the user understands what it means to create an Organization.
=> add organization create command [EH-388]

aiven/client/cli.py, aiven/client/client.py
add organization edit command [EH-389]
[EH-389]
[EH-389]: https://aiven.atlassian.net/browse/EH-389?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> add organization edit command [EH-389]

aiven/client/cliarg.py
CLI args use `-` as word separator, some `_` slipped in.
=> fix organization id args to use `-` instead of `_`

.github/workflows/build.yaml, .github/workflows/publish-pypi.yaml, README.rst, aiven/client/argx.py, aiven/client/cli.py, aiven/client/client.py, mypy.ini, pyproject.toml, tests/test_argx.py
Python 3.7 recently reached its end-of-life:
https://devguide.python.org/versions/#versions
=> Drop Python 3.7 support

aiven/client/argx.py, aiven/client/cli.py, aiven/client/cliarg.py, aiven/client/client.py
- `--parent-id` option added to the project create.
- `--account-id` option is marked as deprecated with deprecation
warning on project create.
[EH-573]
[EH-573]: https://aiven.atlassian.net/browse/EH-573?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add --parent-id to project create [EH-573]

.github/workflows/build.yaml
pypy has a version for Python 3.10, let's use it.
=> Add pypy-3.10 to GitHub Actions

aiven/client/client.py
Change the type annotation for `client.create_project`.
According to [API specification](https://api.aiven.io/doc/#tag/Project/operation/ProjectCreate), `use_source_project_billing_group` argument is `bool`, not `str`.
=> Fix typing for use_source_project_billing_group argument

aiven/client/cli.py, aiven/client/cliarg.py, aiven/client/client.py, tests/test_cli.py
The client doesn't resolve the priorities if both `--replication` and `--retention-ms` are provided, the API does (in favor of the latter).
=> Support setting Kafka topic retention in milliseconds

aiven/client/cli.py, aiven/client/cliarg.py, aiven/client/client.py, tests/test_cli.py
`remote.storage.enable`, `local.retention.ms`, `local.retention.bytes`.
=> Support setting Kafka tiered storage topic configs

aiven/client/client.py, tests/test_cli.py, tests/test_client.py
In HTTP/1.1 Content-Length is not always required to be sent by the server - if chunked transfer encoding is used, the Content-Length header can be omitted, and instead length indicated as part of each chunk. Chunked transfer encoding is [always acceptable in HTTP/1.1][1] so by effectively requiring a Content-Length header we are breaking compliance with the spec.
We have avoided this biting us, purely by accident so far due to the web server used for our API, but it will cause problems in the future. Basically, we shouldn't try and figure out the content length by parsing headers in our code, but instead rely on the Requests library which has logic to calculate the correct value based on the HTTP spec.
[1]: https://datatracker.ietf.org/doc/html/rfc9112#section-7.4-2
=> Fix API client compliance with HTTP/1.1

aiven/client/client.py
Removes `account_id` enforcement at the SDK on project creation
[EH-776]
[EH-776]: https://aiven.atlassian.net/browse/EH-776?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Remove account_id enforcement from client on project create

Makefile, README.rst, aiven/client/cli.py, aiven/client/client.py, pyproject.toml, tests/test_cli.py, tests/test_client.py
This commit adds custom file support for Aiven services
=> Add custom files API support

aiven/client/cli.py, aiven/client/cliarg.py, aiven/client/client.py
We want to keep the user experience for authentication-methods in the console.
Therefore we should remove the functionality from the cli.
[EH-829]
[EH-829]: https://aiven.atlassian.net/browse/EH-829?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Remove avn account authentication-method

aiven/client/cli.py
Re: kafka tiered storage. 
Get topic API will include `remote_size` to show amount of stored information on remote storage. This PR extends the layout to show this value.
=> feat: add partition remote_size to get topic command

aiven/client/cli.py, aiven/client/client.py, tests/test_cli.py
Add two new commands to assess carbon impact of Aiven services. The two commands are:
1. Command to project or predict typical emissions for a given service type, plan and cloud selection, and
2. Command to assess project actual emissions over a time period
The backend reporting functionality is still considered experimental, and we're working to ensure validation on the returned numbers.
=> Initial commands on the sustainability APIs

aiven/client/cli.py, aiven/client/client.py
Opensearch security plugin for the Aiven for Opensearch has been introduced with API to query the status and enable the functionality. This adds the matching commands to the client.
=> Add support for Opensearch Security Management API

README.rst
GH action to publish a new release to PyPi failed with:
ERROR    `long_description` has syntax errors in markup and would not be
rendered on PyPI.
line 365: Warning: Literal block ends without a blank line; unexpected
unindent.
Add the empty line at the end of the literal block.
Also adjust the length of the underlining for the title above, it does not seem to count as a syntax error, but is consistent with the rest of the README.
=> Fix README.rst syntax

aiven/client/_typing.py, aiven/client/client.py, tests/test_client.py
To allow controlling retry behavior, this commit adds the ability to pass in a `RetrySpec` when instantiating `AivenClient`. This maintains existing behavior for all current instantiations, but when configured this overrides these properties of all calls made through the client:
- Passing `RetrySpec(http_methods=("GET", "PUT"))` will make the client use retries for PUT in addition to the default GET.
- Passing `RetrySpec(sleep=timedelta(seconds=1))` changes sleep time in between retries to 1 second for GET calls, other methods will have no retries.
- Passing `RetrySpec(attempts=5)` changes the number of attempts for GET calls, other methods will have no retries.
- Passing `RetrySpec(attempts=5, sleep=timedelta(seconds=1), http_methods=("GET", "PUT"))` will set the configured values for …
=> feature: Expose retry paramater for update_service_topic

aiven/client/cliarg.py
Just a minor fix of the 'avn service list --help' output.
There was a reference to 'avn service list-types' to list types of services. The correct command is 'avn service types'.
This change is in accordance with the documentation at [https://aiven.io/docs/tools/cli/service-cli](https://aiven.io/docs/tools/cli/service-cli#avn-cli-service-type)
=> Fix service help text reference to positional argument 'service types'

.github/workflows/build.yaml, Makefile, aiven/client/cli.py, aiven/client/client.py, tests/test_cli.py
In order to provision a Google BYOC we need to pass the customer's privilege-bearing service account ID, so we can later impersonate it and start service node instances in the Google account of the customer.
Also, ease local testing:
- replace 'pip install -e .[dev]' by 'make install-py'
- create a default 'make' target to locally run: install-py, validate-style, lint and test
[MILK-135]
[MILK-135]: https://aiven.atlassian.net/browse/MILK-135?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> client: allow to provision Google BYOC [MILK-135]

Makefile, README.rst, aiven/client/cli.py
With the release of [Aiven for Valkey](https://aiven.io/docs/products/valkey), it's possible to create Valkey ACL users via the API. 
- enable Valkey ACL user creation and editing via the aiven client
- replace Redis ACL user example with Valkey
- fix `make ruff` recipe
=> Add support for Valkey ACL users

aiven/client/cli.py, aiven/client/client.py
Client and SDK additions to support service account key management for AlloyDB Omni AI model integrations.
=> client: alloydb omni private key management [BF-2808]

aiven/client/cli.py
Customers are used to set environment so they don't have to pass all arguments for each aiven-client command they run. This PR takes the current project into account in flink commands.
[PM-4549]
[PM-4549]: https://aiven.atlassian.net/browse/PM-4549?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> client: flink commands ignore the current project

aiven/client/cli.py, aiven/client/client.py, tests/test_cli.py
Add the following `service` subcomands `kafka-acl-list` `kafka-acl-add` `kafka-acl-delete`.
=> Add cli support for Apache Kafka native ACLs

aiven/client/cli.py
Fix the help string for `--cluster` option of `avn service kafka-service-add`.
=> Fix help string for cluster option in Apache Kafka native ACLs

aiven/client/cli.py
Added support of MySQL CLI client for "avn service cli"
Generated command: 
`MYSQL_PWD=<PWD> mysql -h <HOST> -P <PORT> -u <USER>`
=> Add MySQL client support for "avn service cli" cmd

aiven/client/argx.py, aiven/client/cli.py, aiven/client/client.py, tests/test_cli.py, tests/test_client.py
We're adding `avn service privatelink aws refresh <service>`.
The command `privatelink refresh` already exists for Azure and Google, because these cloud providers don't have a notification system like AWS SQS queue. AWS SQS queue events are used to notify Aiven when a privatelink is changed. We use these events to refresh the corresponding privatelink object.
Explicitly exposing the `refresh` command for AWS will allow two things:
* support PrivateLink for AWS BYOC without AWS SQS queues to start with. AWS SQS queues for BYOC can be implemented later,
* support the manual refresh of PrivateLink connections in case the SQS queue system (used for PrivateLink in Project VPC) is down.
[MILK-425]
[MILK-425]: …
=> client: allow 'privatelink refresh' for AWS [MILK-425]

aiven/client/client.py
Both `get_service_integration_endpoints` (plural) and `get_service_integration_endpoint` (singular) are available in the API, but only the former is supported. Adding the latter with this PR.
=> Add get_service_integration_endpoint to client

.github/workflows/publish-pypi.yaml
=> Update actions/setup-python@v1 Python version

aiven/client/cli.py
When called with `-v` the `service types` command failed for me with
```
File "/usr/lib/python3.12/site-packages/aiven/client/cli.py", line 889, in service__types
title=spec["title"],
~~~~^^^^^^^^^
KeyError: 'title'
```
It seems service config option specifications don't always contain the "title" property. Remove the assumption that it's always there, keeping the current output format if it is.
=> Fix `service types` output when called with `-v` for verbose output

aiven/client/cli.py
Copy-paste typo gets displayed by `avn service --help`.
=> Fix a typo in service__task_get help text

aiven/client/cli.py, aiven/client/client.py
Add support for Aiven OpenSearch Custom Repo API, which includes listing custom repositories in OpenSearch and creating and restoring snapshots with it.
bonus: refactoring of cli/client modules by splitting it to base/common classess and making them extendable with service specific commands/endpoints
=> client,cli: add OpenSearch Custom Repo commands

aiven/client/cli.py, aiven/client/client.py
Aiven API has now a _restore endpoint which is not yet supported by aiven-client. This PR should fix that.
=> opensearch: add snapshot restore command

aiven/client/cli.py, aiven/client/client.py
It is possible to configure EOL extensions and also to enable specific versions for selected customers on Aiven backend. 
When creating or updating a service, check for service versions availability including also any account-level configurations.
=> Use default project's account-id to check service versions availability

aiven/client/cli.py, tests/test_cli.py
It might be useful to retrieve information on a given application-user's access token, given it's token-prefix. This can be used, for example, to check when the token was last used, or its expire date.
=> Add command to show info for an application user's token

README.rst
We added the `application-user` commands but didn't include any mention of them in the docs.
=> docs: add application-users section and fix organization argument

aiven/client/cli.py
"never" is not a valid value for maintenance day of week, as shown by our API docs. Remove it from the list of options.
=> Remove invalid maintenance dow value
