aiven/aiven-client

- aiven/client/cli.py
- aiven/client/client.py
Update client in respect with the Aiven credit attribution changes
> client: attribute credits to projects instead of users

- aiven/client/cli.py
- aiven/client/cliarg.py
- aiven/client/client.py
These are the client side changes required to be able to create
service databases and users at will.
> aiven: Add support for service users and service databases

- aiven/client/pretty.py
Allows post processing and printing the entire table in a single statement
to avoid choppy output.
> pretty: add a function for yielding table rows instead of printing them

- aiven/client/cli.py
- aiven/client/cliarg.py
- aiven/client/client.py
Support creating, updating and deleting Kafka topics.
> kafka: topic create, update, delete

- aiven/client/cli.py
- aiven/client/client.py
Possible choices are delete/compact.
> kafka: Allow choosing cleanup policy for a topic at creation time

- aiven/client/argx.py
Previously a function called `service_kafka_topics` would've been exposed as
`avn service kafka-topics` as we didn't allow more levels of subparsers.
Now this can be implemented as `avn service kafka topics`.
> argx: allow more than 1 level of subparsers

- aiven/client/cli.py
- aiven/client/client.py
Four new commands for project VPCs:
- `vpc list`
- `vpc request`
- `vpc peering-connection list`
- `vpc peering-connection request`
> vpc: request and list commands

- aiven/client/cli.py
This makes the use of Java based clients much easier as we create
a suitable keystore/truststore/client properties file for immediate
use.
> client: Add command to create Java keystore/truststore/client properties

- aiven/client/argx.py
- date, datetime to isoformat
- decimal to float
- timedelta to str
> Add custom serializer for various object types

- aiven/client/cli.py
- aiven/client/client.py
Also renames the vpc and peering connection methods/commands from `request` to `create`.
> vpc: delete

- aiven/client/pretty.py
Instead of omitting the first bit of a multi-level key (e.g.
`user_config.pg.max_prepared_transactions`) let's just show the full key
name to make it obvious what the line is about.
This also simplifies the way we format those rows, and fixes some cases
where vertical width ended up being 0 causing a ValueError.
> pretty: show the full key name and fix exceptions for multi-line tables

- aiven/client/cli.py
When fetching logs with `-f` (follow indefinitely), retry requests on errors. Transient network failures will stop fetching logs, but it makes more sense to print a warning to stderr and retry.
Using stderr for warning message so that
> avn service logs servicename -f > logfile
works without having extra error messages printed to the file.
> Retry on network errors when fetching logs with -f

- aiven/client/cli.py
These commands are used by Aiven Terraform integration to produce metadata files for user configuration options.
> Add commands for listing integration and integration endpoint types

- aiven/client/argx.py
For example:
```
> python -m aiven.client service logs --help
...
-S {desc,asc}, --sort-order {desc,asc}
Sort direction for log fetching (default: asc)
-n LIMIT, --limit LIMIT
Get up to N rows of logs (default: 100)
...
```
> show default values in help for integers and non-empty strings

- aiven/client/client.py
v1 api is available as of today, start using it.
> api_prefix: switch to v1

- aiven/client/cli.py
- aiven/client/cliarg.py
- aiven/client/client.py
> Add support for Kafka connect connectors.

- aiven/client/cli.py
- aiven/client/cliarg.py
- aiven/client/client.py
> Add support for Kafka Schema Registry

- aiven/client/cli.py
Make the verbose output for service display individual nodes belonging
to the service as well as their states. State specific progress details
are also shown when available.
Creating as draft since the server side functionality isn't available just yet.
> Show state for individual service nodes

- aiven/client/cli.py
- aiven/client/client.py
Added new generic query statistics APIs which CLI is now using.
Old APIs which are harcoded for PostgreSQL (pg) are now deprecated.
> Add support for querying MySQL query statistics.

- aiven/client/cli.py
> Fix topic-get exception when (latest_)offset is None

- aiven/client/cli.py
- aiven/client/client.py
If password is not given, a random one will be generated, as before.
> Add option to set new password for service user credentials reset

- aiven/client/cli.py
- aiven/client/cliarg.py
- aiven/client/client.py
Draft because this is pending for some server changes
> Support for account and authentication method management

- aiven/client/cli.py
- aiven/client/client.py
The `user_peer_network_cidrs` property for VPC peering connections is
supported for connection create and get commands.
> vpc: user-defined peer network cidrs

- aiven/client/cli.py
- aiven/client/client.py
Supported in the CLI with the `vpc user-peer-network-cidr add` and
`delete` commands.
> vpc: update user-defined peer network cidrs

- .isort.cfg
- .travis.yml
- Makefile
- aiven/__init__.py
- aiven/client/argx.py
- aiven/client/cli.py
- aiven/client/cliarg.py
- aiven/client/client.py
- aiven/client/pretty.py
- tests/test_cli.py
- tests/test_pretty.py
- Remove python2 compat code
- Automatically reorder imports
> Misc cleanups

- README.rst
I was going through the README and I noticed a couple of things and I took the liberty to send this PR in the hope it would improve the document from a reading standpoint :)
> Fix typo + standardise acronyms & code formatting

- README.rst
- aiven/client/argx.py
- scripts/avn
> Add optional shell completions

- .gitignore
- DEVELOPMENT.rst
> Add development guidelines

- README.rst
- aiven/client/cli.py
- aiven/client/cliarg.py
- aiven/client/client.py
Added `avn account team` commands to manage teams, team membership and attaching/detaching team to the project.
https://app.clubhouse.io/aiven/story/11901/avn-add-account-teams-commands
> cli: add account team commands

- aiven/client/argx.py
- aiven/client/cli.py
- aiven/client/client.py
Subcommands to update integration or integration endpoint fail with an `UnboundLocalError` unless config variables are also supplied.
Also removed redundant parentheses.
> cli: fix unbound variables, formatting

- aiven/client/cli.py
> Handle missing cert and key in user-creds-download

- README.rst
- aiven/client/cli.py
- aiven/client/client.py
Supported for Redis services running version 6 and above.
> cli: add support for creating Redis users with ACL rules

- aiven/client/cli.py
- aiven/client/cliarg.py
- aiven/client/client.py
Add support for M3 namespaces.
Added commands: avn service m3 namespace {add, delete, list}
> cli: support for m3 namespaces

- aiven/client/cli.py
Was broken in #159 / 51b30e6 (change halfway)
> cli: Fix service_name usage

- aiven/client/cli.py
3d2b577 either shouldn't have touched some of these, or the arg rename was incomplete.
> cli: fix some `service` and `project` subcommands

- aiven/client/cli.py
Revert some more of 3d2b5771, which did a bit too much of search & replacing.
> Fix some account commands.

- aiven/client/cli.py
Revert some more of 3d2b5771, which did a bit too much of search & replacing.
> Fix card commands

- aiven/client/cli.py
- aiven/client/client.py
Adds commands and library methods for managing AWS Private Link VPC
endpoint services
> cli: aws privatelink support

- aiven/client/cli.py
- aiven/client/cliarg.py
- aiven/client/client.py
> Add (billing|tech)_email_address to project ops

- SECURITY.md
Add security policy with advise on reporting possible vulnerabilities.
> security: add security policy

- README.rst
A revisit of the README to try to get the user onboarded more smoothly, and to add some additional resources that they might find useful.
> Refactor the README

- aiven/client/cli.py
- aiven/client/speller.py
- tests/test_speller.py
I used the code of Norvig, as it's small, and I didn't want to introduce additional dependency.
> Add "did you mean" hint on wrong option selection

- README.rst
> Fix CI badge point to GitHub Actions instead of Travis CI

- .gitignore
- aiven/client/cli.py
- aiven/client/cliarg.py
- aiven/client/client.py
- tests/test_cli.py
Add support for adding tags to topic while creating topics and adding, removing and updating tags while updating topics.
> cli: add support for topic tags

- README.rst
I keep finding out about these awesome additional features so I thought I'd write them down in case anyone else needs to find them as well!
> Add some notes about the auth helper features in avn

- aiven/client/cli.py
Fix documentation, the comment for billing group update was not correct
> Fix documentation, the comment for billing group update was not correct

- README.rst
- aiven/client/cli.py
Provide support to provide channels' ACL for Redis users.
> Add support for setting Redis ACL channels

- aiven/client/argx.py
- tests/test_argx.py
Plugins rely on the ability to delay evaluation of `@property` values until after scanning and set-up of plugin classes is complete. However, some related descriptor types like `@cached_property` are not actually instances of the `property` class at all. This has caused problems downstream with a [bug](https://aiven.atlassian.net/browse/SRES-1314) where access to potentially not configured databases fails during the execution of unrelated commands, because the scanning of the plugin classes coerces these alternative descriptors to values, forcing early evaluation of their methods.
This change generalizes the delay-of-evaluation check from an `isinstance()` to duck-typing the attribute for being a [data descriptor](https://docs.python.org/3/howto/descriptor.html#descriptor-protocol). Both …
> argx: skip all descriptors when scanning plugin objects (SRES-1381)

- aiven/client/cli.py
- aiven/client/cliarg.py
- aiven/client/client.py
Adds support for two new API features:
* Static IP addresses for services
* Azure privatelink management
> Static IP address and Azure privatelink support

- aiven/client/cli.py
- aiven/client/cliarg.py
- aiven/client/client.py
Add support for a new feature that allows increasing the disk space provided by the plan within the plan defined limits.
> cli: add support for dynamic disk sizing

- aiven/client/cli.py
- aiven/client/client.py
- tests/test_speller.py
__WHY__:
New Flink service will be released soon
__WHAT__:
Add Flink CLI support for existing REST API endpoints.
> flink: add supported methods

- aiven/client/cli.py
- aiven/client/client.py
See individual commits for details and examples.
> flink: add job listing and fetching

- Makefile
New version of Flink service API
> Version 2.14.4 release

- Makefile
Update version to 2.14.5 for new release
> Version 2.14.5 release

- aiven/client/argx.py
- aiven/client/pretty.py
- mypy.ini
Partial implementation of #258.
> Add type annotations for aiven.client.argx

- aiven/client/cliarg.py
- aiven/client/connection_info/_utils.py
- aiven/client/connection_info/common.py
- aiven/client/connection_info/kafka.py
- aiven/client/connection_info/pg.py
- mypy.ini
Partial implementation of #258.
> Add type annotations for aiven.client.cliarg and aiven.client.connection_info

- .gitignore
- aiven/client/argx.py
- aiven/client/cli.py
- aiven/client/pretty.py
- mypy.ini
- requirements.dev.txt
- tests/test_argx.py
- tests/test_cli.py
- tests/test_cliarg.py
- tests/test_session.py
Add type annotations to:
- `test_argx.py`
- `test_cli.py`
- `test_cliarg.py`
- `test_session.py`
[DARK-557]
[DARK-557]: https://aiven.atlassian.net/browse/DARK-557?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add type annotations to tests

- aiven/client/client.py
- tests/test_cli.py
[DARK-637]
[DARK-637]: https://aiven.atlassian.net/browse/DARK-637?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Show all results for static ips list

- mypy.ini
- version.py
> Finalize type annotations

- aiven/client/argx.py
Small change that makes the code more readable and reusable.
> cli: isolated name to cmd parts conversion

- aiven/client/cli.py
> Fix pylint error

- aiven/client/cli.py
- aiven/client/client.py
- tests/test_cli.py
~⚠️  Please, don't merge it yet! ⚠️~
Part of the SBOM functionality already implemented.
See [SECDEV-889]
[SECDEV-889]: https://aiven.atlassian.net/browse/SECDEV-889?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Implement the SBOM functionality in aiven-client

- aiven/client/cli.py
- aiven/client/client.py
We have a pw change API, but client was missing a command for it. Add one.
> Add a command to change user password

- aiven/client/cli.py
- aiven/client/client.py
- tests/test_cli.py
To be able to edit existing oauth2 clients fixing improving title and descriptions
> Add command to update oauth2 client [EH-441]

- aiven/client/cli.py
- aiven/client/client.py
This PR adds the organization listing command.
> Add organization listing command [EH-375]

- .pylintrc
- aiven/client/cli.py
- aiven/client/cliarg.py
- aiven/client/client.py
- tests/test_client.py
[EH-288]
[EH-288]: https://aiven.atlassian.net/browse/EH-288?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add organization user list and invite commands [EH-288]

- aiven/client/pretty.py
- tests/test_pretty.py
Alternative to #337
Properly handle the case in which `table_layout` in `aiven.client.pretty.print_table` include a column whose value is a dict
object: in this case the dict will be serailized to a JSON string an added to the resulting table.
For example, consider the following:
```
rows = []
rows.append(
{
"ip": ipaddress.IPv4Address("192.168.16.1"),
"network": ipaddress.IPv4Network("192.168.16.0/20"),
"metric": {"qos": 1, "ping": 3},
"next_hop_ip": ipaddress.IPv4Address("192.168.16.2"),
"next_hop_mac": "0c:d0:f8:a3:04:31",
"function1": test_print_table,
}
)
rows.append(
{
"ip": ipaddress.IPv4Address("10.0.0.1"),
"network": ipaddress.IPv4Network("10.0.0.0/16"),
"metric": {"ping": 100},
"function2": test_print_table,
}
)
print_table(rows, table_layout=["ip", "metric", "network"])
```
The …
> Handle dict value for column in table_layout

- aiven/client/cli.py
- aiven/client/cliarg.py
- aiven/client/client.py
[EH-390]
[EH-390]: https://aiven.atlassian.net/browse/EH-390?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> add organization delete [EH-390]

- aiven/client/cli.py
- aiven/client/cliarg.py
- aiven/client/client.py
Adds user group commands list, show, create, update and delete.
[EH-516]
[EH-516]: https://aiven.atlassian.net/browse/EH-516?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> add user groups commands [EH-516]

- aiven/client/cli.py
- aiven/client/client.py
The following organization payment method commands are added.
- `avn organization --organization-id XYZ card list`
- `avn organization --organization-id XYZ card create`
- `avn organization --organization-id XYZ card delete`
[EH-501]
[EH-501]: https://aiven.atlassian.net/browse/EH-501?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> add organization payment method commands [EH-501]

- aiven/client/cli.py
- tests/test_cli.py
Organization have tiers now
[EH-537]
[EH-537]: https://aiven.atlassian.net/browse/EH-537?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add tier to organization list [EH-537]

- aiven/client/cli.py
- aiven/client/client.py
- tests/test_cli.py
Make these operations available from the CLI.
> Add clickhouse database create/delete/list

- pyproject.toml
Update dev dependencies to match downstream.
> Update dev dependencies

- aiven/client/cli.py
The CLI command `avn service user-kafka-java-creds` fails with a confusing error message when the value of argument --username does not match an existing service user name.
[HH-2459]
[HH-2459]: https://aiven.atlassian.net/browse/HH-2459?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> client: handle wrong service user in user-kafka-java-creds [HH-2459]

- aiven/client/cli.py
- aiven/client/client.py
- tests/test_cli.py
This adds initial support for Bring Your Own Cloud (https://aiven.io/docs/platform/concepts/byoc) APIs.
> Add initial support for Bring Your Own Cloud related APIs

- aiven/client/cli.py
Fix service topic-get in JSON mode to print valid JSON [HH-5310]
If JSON output is requested, print a single valid JSON object as output from `avn service topic-get`.
[HH-5310]: https://aiven.atlassian.net/browse/HH-5310?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix service topic-get in JSON mode to print valid JSON [HH-5310]

- aiven/client/cli.py
Make it possible to list available service versions for a specific project. This will take into consideration any excpetion configured for service versions availability configured on the project's account.
> List service versions per project

- DEVELOPMENT.rst
Add instruction on how to release a new version.
> Add release instructions
